{% set name = "psij-rest" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/psij-rest-{{ version }}.tar.gz
  sha256: c3b53eb7688fce86fda4002a9cbd8e118eb178aac886ae55c3244165c46e3545

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - psij-python
    - requests
    - websocket

test:
  imports:
    - psij
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/exaworks/psij-rest
  summary: This is an implementation of the PSI/J (Portable Submission Interface for Jobs)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
